# Generated by Django 5.2.7 on 2025-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('CHENNAI', 'chennai'), ('HYDERABAD', 'hyderabad'), ('BANGALORE', 'bangalore'), ('COIMBATORE', 'coimbatore'), ('MUMBAI', 'mumbai'), ('DELHI', 'delhi'), ('JAIPUR', 'jaipur'), ('KOLKATA', 'kolkata'), ('PONDICHERRY', 'pondicherry')], max_length=50)),
                ('to_location', models.CharField(choices=[('BANGALORE', 'bangalore'), ('VIJAYAWADA', 'vijayawada'), ('MADURAI', 'madurai'), ('GOA', 'goa'), ('AGRA', 'agra'), ('UDAIPUR', 'udaipur'), ('DARJEELING', 'darjeeling'), ('CHENNAI', 'chennai'), ('KOLKATA', 'kolkata'), ('PONDICHERRY', 'pondicherry')], max_length=50)),
                ('bus_number', models.CharField(max_length=50)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('journey_date', models.DateField()),
                ('seats_booked', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
